### ISSUE TITLE
Automatically generating new queues

### ISSUE THREAD

**Issue by FrEaKmAn** [hugocore/kairosdb-rabbitmq#2]
Hi

We have multiple sensors which log data. We add new sensors via our dashboard. Each sensor has it's own metric (sensor.1.data, sensor.2.data, ..).

Is there a way to automatically add new queues without manually writing them in bindings.json and restarting KairosDB?

Do you think it would make sense to manually create a queue in rabbitmq and then fire an event (custom API endpoint) to notify plugin to reload queues list?

**Comment by hugocore** [comment]
Hi,

So sorry for the late response!! I haven't received any notification about your question. I am sure you are probably not interested anymore in my reply, but just for future queries from other users: yes, this can be done.

Instead of reading the binding configuration from a file you can read it from an external system/api like redis. Like so, you could change the binding between queues and messages on the fly. You would have to update this method I believe: https://github.com/hugocore/kairosdb-rabbitmq/blob/ebe9209fda2f1ddb4615cc312e4ef0bb60008cb3/src/main/java/org/kairosdb/plugin/rabbitmq/core/RabbitmqConsumer.java#L348

Cheers
